# Generated by Django 4.1.4 on 2022-12-11 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=15)),
                ('model', models.CharField(max_length=15)),
                ('body_style', models.CharField(blank=True, choices=[('Cargo van', 'Cargo van'), ('Combi', 'Combi'), ('Coupe', 'Coupe'), ('Hatchback', 'Hatchback'), ('Minivan', 'Minivan'), ('SUV', 'SUV'), ('Sedan', 'Sedan'), ('Wagon', 'Wagon')], max_length=9, null=True)),
                ('km', models.CharField(max_length=15)),
                ('first_reg_date', models.DateField()),
                ('transmission', models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], max_length=9)),
                ('fuel', models.CharField(choices=[('Diesel', 'Diesel'), ('Gasoline', 'Gasoline'), ('Hybrid', 'Hybrid'), ('Electric', 'Electric')], max_length=8)),
                ('color', models.CharField(max_length=15)),
                ('price', models.CharField(max_length=15)),
                ('photo1', models.URLField()),
                ('photo2', models.URLField(blank=True, null=True)),
                ('photo3', models.URLField(blank=True, null=True)),
                ('photo4', models.URLField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
